canonical: http://hl7.org/fhir/uv/ips
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
id: hl7.fhir.uv.ips
name: InternationalPatientSummaryIG
title: International Patient Summary Implementation Guide
status: active
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg
    valueCode: pc
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 2
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
license: CC0-1.0
version: 2.0.0-ballot
copyrightYear: 2020+
releaseLabel: ci-build
publisher:
  name: HL7 International / Patient Care
  url: http://www.hl7.org/Special/committees/patientcare
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World"
dependencies:
  hl7.terminology.r4:
    version: 5.5.0
    uri: http://terminology.hl7.org/ImplementationGuide/hl7.terminology
    id: hl7tx
  hl7.fhir.uv.extensions.r4:
    version: 5.1.0
    uri: http://hl7.org/fhir/extensions/ImplementationGuide/hl7.fhir.uv.extensions
    id: hl7ext
  fhir.dicom:
    version: 2024.2.20240331
    uri: http://fhir.org/packages/fhir.dicom/ImplementationGuide/fhir.dicom
menu:
  Home: index.html
  Table of Contents: toc.html
  General Principles and Design:
    General Principles: principles.html
    Design Conventions: design.html
    Generation and Data Inclusion: ipsGeneration.html
    Privacy and Security Considerations: considerations.html
    Known Issues and Future Development: knownIssues.html
  The "IPS": ipsStructure.html
  FHIR Artifacts:
    The IPS Composition: StructureDefinition-Composition-uv-ips.html
    IPS Library: profiles.html
    Datatypes: datatypes.html
    Extensions: extensions.html
    Terminology: terminology.html
    Examples: examples.html
  Downloads: downloads.html
  Copyrights: copyrights.html
  Change Log: changes.html
resources:
  Bundle/IPS-examples-Bundle-01:
    name: 'IPS Bundle example'
    description: 'IPS Bundle example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Bundle-uv-ips
  Bundle/IPS-examples-Bundle-with-immunization:
    name: 'IPS Bundle example with Immunization'
    description: 'IPS Bundle example with Immunization section'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Bundle-uv-ips
  Bundle/bundle-no-info-required-sections:
    name: 'IPS Bundle example - no information in required sections'
    description: 'IPS Bundle example - no information in required sections'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Bundle-uv-ips
  Bundle/bundle-minimal:
    name: 'IPS Bundle example - minimal'
    description: 'IPS Bundle example - minimal'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Bundle-uv-ips
  Composition/composition-minimal:
    name: 'IPS Composition example - minimal'
    description: 'IPS Composition example - minimal'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Composition-uv-ips
  Medication/eumfh-39-07-1:
    name: 'Medication : Simvastatin 40 MG Disintegrating Oral Tablet'
    description: 'Medication : Simvastatin 40 MG Disintegrating Oral Tablet'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Medication-uv-ips
  MedicationStatement/eumfh-39-07-1:
    name: 'MedicationStatement: on-going Simvastatin treatment'
    description: 'MedicationStatement: on-going Simvastatin treatment'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/MedicationStatement-uv-ips
  MedicationRequest/eumfh-39-07-1-request:
    name: 'MedicationRequest: Simvastatin request'
    description: 'MedicationRequest: Simvastatin request'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/MedicationRequest-uv-ips
  Immunization/75680:
    name: 'Immunization: Vaccin anti diphtérie-coqueluche-tétanos-poliomyélite (Luxembourg)'
    description: 'Immunization: Vaccin anti diphtérie-coqueluche-tétanos-poliomyélite (Luxembourg)'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Immunization-uv-ips
  AllergyIntolerance/eumfh-39-07-1:
    name: 'AllergyIntolerance: No known allergies'
    description: 'AllergyIntolerance: No known allergies'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/AllergyIntolerance-uv-ips
  AllergyIntolerance/allergyintolerance-with-abatement:
    name: 'AllergyIntolerance: resolved allergy'
    description: 'AllergyIntolerance: resolved allergy'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/AllergyIntolerance-uv-ips
  AllergyIntolerance/allergyintolerance-multiple-codings:
    name: 'AllergyIntolerance: multiple codings'
    description: 'AllergyIntolerance: multiple codings'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/AllergyIntolerance-uv-ips
  Condition/eumfh-39-07-1:
    name: 'Condition: Acute myocardial infarction of anterior wall'
    description: 'Condition: Acute myocardial infarction of anterior wall'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Condition-uv-ips
  Procedure/eumfh-39-07-1:
    name: 'Procedure: Surgical procedure'
    description: 'Procedure: Surgical procedure'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Procedure-uv-ips
  Practitioner/eumfh-39-07:
    name: 'Practitioner example'
    description: 'Practitioner example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Practitioner-uv-ips
  PractitionerRole/simple-pr:
    name: 'PractitionerRole: simple example'
    description: 'Very Simple PractitionerRole example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/PractitionerRole-uv-ips
  Patient/eumfh-39-07:
    name: 'Patient: male patient'
    description: 'Patient: male patient'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Patient-uv-ips
  Patient/66033:
    name: 'Patient: minimal example'
    description: 'Patient: minimal example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Patient-uv-ips
  Patient/patient-example-female:
    name: 'Patient: female patient'
    description: 'Patient: female patient'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Patient-uv-ips
  DeviceUseStatement/eumfh-70-275-1:
    name: 'DeviceUseStatement: No known devices in use'
    description: 'DeviceUseStatement: No known devices in use'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/DeviceUseStatement-uv-ips
  Device/eumfh-70-275-1:
    name: 'Device: No known devices in use'
    description: 'Device: No known devices in use'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Device-uv-ips
  Device/ips-example-imaging-1:
    name: 'Device: device observer example'
    description: 'Device: device observer example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Device-observer-uv-ips
  Observation/ips-example-imaging-1:
    name: 'Observation: imaging CT Abdomen W contrast IV'
    description: 'Observation: imaging CT Abdomen W contrast IV'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-results-radiology-uv-ips
  Observation/ips-example-imaging-4:
    name: 'Observation: imaging CT Abdomen W contrast IV, sub-observations'
    description: 'Observation: imaging CT Abdomen W contrast IV,sub-observations'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-results-radiology-uv-ips
  ImagingStudy/TII-ImagingStudy-5-1:
    name: 'ImagingStudy: referred DICOM study'
    description: 'ImagingStudy: referred DICOM study'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/ImagingStudy-uv-ips
  Organization/TII-Organization1:
    name: 'Organization: example'
    description: 'Organization: example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Organization-uv-ips
  Organization/simple-org:
    name: 'Organization: simple example'
    description: 'Very Simple Organization example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Organization-uv-ips
  Organization/lab-org-example:
    name: 'Organization: lab example'
    description: 'Best Hospital Lab Organization example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Organization-uv-ips
  Observation/pregnancy-edd-example:
    name: 'Observation: pregnancy edd example'
    description: 'Observation: pregnancy edd example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-pregnancy-edd-uv-ips
  Observation/pregnancy-status-example:
    name: 'Observation: pregnancy status example'
    description: 'Observation: pregnancy status example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-pregnancy-status-uv-ips
  Observation/pregnancy-outcome-example:
    name: 'Observation: pregnancy outcome example'
    description: 'Observation: pregnancy outcome example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-pregnancy-outcome-uv-ips
  Observation/tobacco-use-example:
    name: 'Observation: SH tobacco use example'
    description: 'Observation: SH tobacco use example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-tobaccouse-uv-ips
  Observation/alcohol-use-example:
    name: 'Observation: SH alcohol use example'
    description: 'Observation: SH alcohol use example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-alcoholuse-uv-ips
  Specimen/specimen-example-1:
    name: 'Specimen: example'
    description: 'Specimen: example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Specimen-uv-ips
  Observation/serum-creatinine-adult:
    name: 'Observation: serum creatinine example'
    description: 'Observation: serum creatinine example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-results-laboratory-pathology-uv-ips
  Observation/hemoglobin:
    name: 'Observation: hemoglobin example'
    description: 'Observation: hemoglobin example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-results-laboratory-pathology-uv-ips
  Observation/urine-wbc-range:
    name: 'Observation: urine wbc range example'
    description: 'Observation: urine wbc range example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-results-laboratory-pathology-uv-ips
  Observation/pathology-cancer:
    name: 'Observation: estrogen receptor in tissue example'
    description: 'Observation: estrogen receptor in tissue example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-results-laboratory-pathology-uv-ips
  DiagnosticReport/hemoglobin:
    name: 'DiagnosticReport: hemoglobin example'
    description: 'DiagnosticReport: hemoglobin example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/DiagnosticReport-uv-ips
  Media/media-example-smile:
    name: 'Media: example'
    description: 'Media: example'
    exampleCanonical: http://hl7.org/fhir/uv/ips/StructureDefinition/Media-observation-uv-ips
